repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: "v2.5.0"
  hooks:
    - id: check-merge-conflict
    - id: debug-statements

- repo: local

  hooks:
    # - id: black
    #   name: black
    #   entry: black
    #   language: system
    #   types: [python]
    #   args: [--line-length=79,]

    - id: flake8
      name: flake8
      entry: flake8
      language: system
      types: [python]
      args: [
        "--ignore=E203,W503,FI10,FI11,FI12,FI13,FI14,FI15,FI16,FI17,FI58,PT013",
        "--max-line-length=79",
        "--exclude=tests/*, venv/*"
      ]

    # - id: isort
    #   name: isort
    #   entry: isort
    #   language: system
    #   types: [python]
    #   args: [
    #     --skip test_homework.py,
    #     # --sg venv
      # ]
